In [1]:
import pandas as pd

In [2]:
df =pd.read_csv("spam.csv")

In [3]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [10]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [11]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [15]:
df.to_pickle("spam_0_and_ham_1")

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train ,y_test =train_test_split(df.Message ,df.spam,test_size=0.2)

In [30]:
X_test.head()

344                    Am not interested to do like that.
4854                          I'm fine. Hope you are also
4666                  Ok set let u noe e details later...
1050    18 days to Euro2004 kickoff! U will be kept in...
2896                            Went to ganesh dress shop
Name: Message, dtype: str

In [29]:
type(X_train)

pandas.Series

In [31]:
type(y_train)

pandas.Series

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [33]:
v=CountVectorizer()

In [34]:
X_train_cv = v.fit_transform(X_train.values)

In [38]:
X_train_cv.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3, 7766))

In [40]:
v.get_feature_names_out()[1000:1050]

array(['any', 'anybody', 'anymore', 'anyone', 'anyones', 'anyplaces',
       'anythin', 'anything', 'anytime', 'anyway', 'anyways', 'anywhere',
       'aom', 'apart', 'apartment', 'apes', 'apeshit', 'aphex', 'apnt',
       'apo', 'apologetic', 'apologise', 'apologize', 'apology', 'app',
       'apparently', 'appeal', 'appear', 'appendix', 'applebees',
       'apples', 'application', 'apply', 'applyed', 'applying',
       'appointment', 'appointments', 'appreciate', 'appreciated',
       'approaches', 'approaching', 'appropriate', 'approve', 'approved',
       'approx', 'apps', 'appt', 'april', 'aproach', 'apt'], dtype=object)

In [43]:
v.vocabulary_

{'when': 7507,
 'is': 3768,
 'school': 5969,
 'starting': 6476,
 'where': 7511,
 'will': 7546,
 'you': 7729,
 'stay': 6485,
 'what': 7500,
 'the': 6837,
 'weather': 7453,
 'like': 4134,
 'and': 967,
 'food': 2942,
 'do': 2386,
 'have': 3373,
 'social': 6314,
 'support': 6645,
 'system': 6696,
 'friends': 3018,
 'in': 3659,
 'all': 924,
 'these': 6857,
 'things': 6868,
 'are': 1058,
 'important': 3648,
 'sorry': 6359,
 'da': 2152,
 'today': 6968,
 'wont': 7609,
 'come': 1918,
 'to': 6961,
 'play': 5255,
 'driving': 2473,
 'clas': 1841,
 'freemsg': 3003,
 'hey': 3442,
 'there': 6855,
 'darling': 2178,
 'it': 3780,
 'been': 1292,
 'week': 7467,
 'now': 4857,
 'no': 4807,
 'word': 7615,
 'back': 1199,
 'some': 6324,
 'fun': 3055,
 'up': 7215,
 'for': 2951,
 'still': 6510,
 'tb': 6749,
 'ok': 4934,
 'xxx': 7684,
 'std': 6490,
 'chgs': 1790,
 'send': 6038,
 '50': 543,
 'rcv': 5608,
 'hi': 3445,
 'finally': 2863,
 'completed': 1943,
 'course': 2051,
 'xmas': 7677,
 'prize': 5444,
 'draws': 2458,
 'we': 7445,
 'trying': 7088,
 'contact': 1992,
 'todays': 6969,
 'draw': 2457,
 'shows': 6163,
 'that': 6833,
 'won': 7602,
 '2000': 349,
 'guaranteed': 3277,
 'call': 1619,
 '09058094565': 183,
 'from': 3034,
 'land': 4027,
 'line': 4148,
 'valid': 7276,
 '12hrs': 293,
 'only': 4964,
 'just': 3901,
 'got': 3211,
 'this': 6877,
 'message': 4479,
 'not': 4843,
 'ignoring': 3624,
 'yes': 7715,
 'was': 7421,
 'shopping': 6139,
 'dont': 2424,
 'search': 5994,
 'love': 4253,
 'let': 4108,
 'find': 2866,
 'thats': 6836,
 'why': 7529,
 'its': 3788,
 'called': 1626,
 'falling': 2780,
 'bcoz': 1267,
 'force': 2952,
 'yourself': 7738,
 'fall': 2778,
 'know': 3984,
 'smeone': 6278,
 'hold': 3485,
 'bslvyl': 1544,
 'told': 6978,
 'am': 944,
 'coming': 1923,
 'on': 4952,
 'wednesday': 7464,
 'work': 7617,
 'going': 3182,
 'few': 2836,
 'min': 4506,
 'alright': 934,
 'see': 6010,
 'bit': 1368,
 'right': 5809,
 'meanwhile': 4438,
 'how': 3542,
 'project': 5471,
 'twins': 7120,
 'comin': 1922,
 're': 5612,
 'getting': 3134,
 'worried': 7627,
 'over': 5043,
 'here': 3432,
 'derek': 2267,
 'taylor': 6747,
 'already': 933,
 'assumed': 1117,
 'worst': 7632,
 'yar': 7697,
 'lor': 4231,
 'wait': 7385,
 'my': 4683,
 'mum': 4663,
 'finish': 2871,
 'sch': 5967,
 'then': 6850,
 'lunch': 4286,
 'whole': 7523,
 'morning': 4608,
 'at': 1124,
 'home': 3493,
 'clean': 1848,
 'room': 5846,
 'quite': 5558,
 'hee': 3407,
 '000': 1,
 'cash': 1686,
 'or': 4991,
 'claim': 1836,
 'call09050000327': 1620,
 'rstm': 5866,
 'sw7': 6665,
 '3ss': 477,
 '150ppm': 313,
 'with': 7576,
 'karnan': 3924,
 'car': 1661,
 'please': 5264,
 'till': 6925,
 '6pm': 614,
 'directly': 2347,
 'goto': 3216,
 'doctor': 2393,
 'vijay': 7322,
 'talk': 6720,
 'jaya': 3826,
 'tv': 7112,
 'doing': 2411,
 'queen': 5549,
 'royal': 5861,
 'wedding': 7461,
 'nokia': 4817,
 '7250i': 621,
 'get': 3127,
 'win': 7549,
 'our': 5024,
 'free': 2996,
 'auction': 1142,
 'take': 6713,
 'part': 5105,
 '86021': 692,
 'hg': 3444,
 'suite342': 6613,
 '2lands': 404,
 'row': 5858,
 'w1jhl': 7370,
 '16': 320,
 'oclock': 4905,
 'mine': 4512,
 'bash': 1242,
 'out': 5027,
 'flat': 2898,
 'plan': 5249,
 'moji': 4581,
 'more': 4604,
 'than': 6821,
 'words': 7616,
 'rich': 5805,
 'day': 2192,
 'miles': 4502,
 'smiles': 6282,
 'made': 4322,
 'frm': 3024,
 'same': 5921,
 'letters': 4111,
 'but': 1586,
 'difference': 2323,
 'smile': 6280,
 'ur': 7231,
 'face': 2760,
 'keeps': 3935,
 'me': 4429,
 'happy': 3349,
 'even': 2672,
 'though': 6888,
 'away': 1175,
 'keep': 3933,
 'smiling': 6284,
 'good': 3194,
 'nyt': 4887,
 'slept': 6253,
 'thinkthis': 6873,
 'time': 6927,
 'lt': 4277,
 'gt': 3274,
 'pm': 5279,
 'dangerous': 2170,
 'prakesh': 5379,
 'generally': 3115,
 'isn': 3775,
 'one': 4958,
 'an': 964,
 'uncountable': 7173,
 'noun': 4854,
 'dictionary': 2310,
 'pieces': 5227,
 'of': 4909,
 'research': 5754,
 'atleast': 1130,
 'once': 4956,
 'otherwise': 5020,
 'miss': 4531,
 'your': 7734,
 'best': 1327,
 'friend': 3017,
 'world': 7624,
 'shakespeare': 6090,
 'shesil': 6112,
 'omw': 4951,
 'castor': 1692,
 'phony': 5207,
 '350': 452,
 'award': 1173,
 'voda': 7347,
 'numbers': 4872,
 'ending': 2600,
 'xxxx': 7686,
 'selected': 6024,
 'receive': 5648,
 'if': 3620,
 'match': 4398,
 '08712300220': 101,
 'quoting': 5565,
 'code': 1894,
 '3100': 443,
 'standard': 6466,
 'rates': 5600,
 'app': 1024,
 'oh': 4930,
 'ya': 7692,
 'hip': 3458,
 'hop': 3510,
 'open': 4973,
 'haha': 3310,
 'thinking': 6871,
 'can': 1642,
 'go': 3171,
 'jazz': 3829,
 'zoom': 7761,
 'cine': 1830,
 'actually': 815,
 'tonight': 6994,
 'leh': 4095,
 'kb': 3930,
 'lesson': 4106,
 'nah': 4694,
 'man': 4355,
 'meant': 4437,
 'be': 1272,
 'crammed': 2066,
 'full': 3052,
 'people': 5162,
 'as': 1091,
 'per': 5164,
 'request': 5748,
 'melle': 4457,
 'oru': 5014,
 'minnaminunginte': 4518,
 'nurungu': 4874,
 'vettam': 7308,
 'has': 3359,
 'set': 6063,
 'callertune': 1629,
 'callers': 1628,
 'press': 5415,
 'copy': 2019,
 'yay': 7701,
 'party': 5112,
 'together': 6972,
 'lol': 4210,
 'trust': 7083,
 'well': 7480,
 'gonna': 3192,
 'check': 1765,
 'steam': 6494,
 'sales': 5914,
 'pee': 5155,
 'so': 6312,
 'text': 6808,
 'want': 7408,
 'too': 6998,
 'baby': 1195,
 'promise': 5475,
 'treat': 7061,
 'bet': 1329,
 'care': 1665,
 '146tf150p': 303,
 'should': 6151,
 'sale': 5913,
 'auntie': 1149,
 'huai': 3559,
 'juan': 3887,
 'never': 4768,
 'pick': 5217,
 'her': 3431,
 'phone': 5203,
 'also': 936,
 'piece': 5226,
 'chachi': 1727,
 'tried': 7068,
 'calling': 1632,
 'unable': 7163,
 'reach': 5613,
 'pl': 5244,
 'give': 3155,
 'missed': 4533,
 'cal': 1613,
 'tiz': 6946,
 'msg': 4638,
 'kanagu': 3919,
 'reckon': 5657,
 'need': 4740,
 'town': 7030,
 'by': 1602,
 'eightish': 2568,
 'walk': 7392,
 'carpark': 1680,
 'machan': 4315,
 'gym': 3300,
 'tomorrow': 6988,
 'wil': 7542,
 'late': 4049,
 'goodnight': 3199,
 'anything': 1007,
 'hello': 3415,
 'fancy': 2789,
 'drink': 2466,
 'something': 6333,
 'later': 4052,
 'registered': 5689,
 'sinco': 6202,
 'payee': 5141,
 'log': 4202,
 'icicibank': 3604,
 'com': 1913,
 'enter': 2623,
 'urn': 7244,
 'confirm': 1971,
 'beware': 1338,
 'frauds': 2990,
 'share': 6098,
 'disclose': 2359,
 'anyone': 1003,
 'watching': 7430,
 'movie': 4628,
 'xy': 7691,
 'wants': 7412,
 'shop': 6137,
 'eh': 2564,
 'din': 2336,
 'sad': 5900,
 'lar': 4039,
 'office': 4919,
 'physics': 5214,
 'don': 2420,
 'tell': 6776,
 'sure': 6651,
 'live': 4177,
 'him': 3455,
 'because': 1280,
 'he': 3384,
 'smokes': 6288,
 'much': 4655,
 'spend': 6406,
 'hours': 3537,
 'begging': 1301,
 'smoke': 6286,
 'cant': 1654,
 'happens': 3345,
 '2waxsto': 426,
 'wat': 7427,
 'she': 6105,
 'ill': 3629,
 'medical': 4443,
 'insurance': 3722,
 'll': 4184,
 'able': 764,
 'deliver': 2245,
 'basic': 1243,
 'currently': 2132,
 'til': 6924,
 'friday': 3015,
 'major': 4346,
 'person': 5180,
 'guide': 3288,
 'jon': 3871,
 'pete': 5188,
 'ive': 3794,
 'bin': 1358,
 'spain': 6383,
 'recently': 5653,
 'hav': 3369,
 'sum': 6617,
 'dinero': 2339,
 'left': 4092,
 'bill': 1353,
 'said': 5908,
 'rents': 5731,
 'mayb': 4421,
 'interested': 3728,
 '12': 283,
 '000pes': 2,
 'around': 1079,
 '48': 513,
 'james': 3812,
 'heard': 3396,
 'about': 766,
 'job': 3854,
 'wildlife': 7545,
 'again': 869,
 'want2come': 7409,
 'that2worzels': 6834,
 'wizzle': 7582,
 'whatever': 7501,
 'wish': 7568,
 'think': 6869,
 'snow': 6308,
 'those': 6885,
 'flurries': 2920,
 'usually': 7261,
 'melt': 4460,
 'before': 1298,
 'they': 6863,
 'hit': 3462,
 'ground': 3264,
 'eek': 2553,
 'haven': 3375,
 'had': 3307,
 'since': 6201,
 'born': 1444,
 'hard': 3350,
 '121': 285,
 'chat': 1757,
 '60p': 580,
 'choose': 1816,
 'girl': 3149,
 'connect': 1980,
 '09094646899': 252,
 'cheap': 1760,
 'uk': 7152,
 'biggest': 1351,
 'service': 6059,
 'vu': 7364,
 'bcm1896wc1n3xx': 1264,
 'dear': 2204,
 'saw': 5953,
 'both': 1449,
 'battery': 1254,
 'low': 4266,
 'who': 7522,
 'were': 7486,
 'tour': 7028,
 'thought': 6889,
 'sofa': 6315,
 'thing': 6867,
 'sent': 6047,
 'curious': 2130,
 'sugar': 6607,
 'having': 3379,
 'number': 4871,
 'sir': 6212,
 'madam': 4321,
 'regret': 5691,
 'disturbance': 2374,
 'might': 4498,
 'reference': 5674,
 'dlf': 2383,
 'premarica': 5397,
 'kindly': 3968,
 'informed': 3695,
 'rgds': 5800,
 'rakhesh': 5584,
 'kerala': 3941,
 'ola': 4941,
 'would': 7639,
 'maybe': 4422,
 've': 7293,
 'his': 3460,
 'direct': 2346,
 'link': 4154,
 'us': 7246,
 'cars': 1682,
 'bids': 1348,
 'online': 4962,
 'arrange': 1080,
 'shipping': 6123,
 'cut': 2141,
 'partnership': 5110,
 'invest': 3742,
 'money': 4591,
 'takes': 6715,
 'rest': 5773,
 'wud': 7662,
 'self': 6026,
 'reliant': 5702,
 'soon': 6350,
 'dnt': 2385,
 'worry': 7629,
 'voice': 7350,
 'speaking': 6391,
 'expression': 2747,
 'childish': 1797,
 'naughty': 4722,
 'sentiment': 6050,
 'rowdy': 5859,
 'ful': 3050,
 'attitude': 1139,
 'romantic': 5843,
 'shy': 6174,
 'attractive': 1140,
 'funny': 3060,
 'irritating': 3765,
 'lovable': 4252,
 'reply': 5741,
 'understand': 7176,
 'loss': 4237,
 'gain': 3072,
 'doesn': 2399,
 'vomit': 7353,
 'temp': 6783,
 'drop': 2476,
 'unmits': 7202,
 'however': 3546,
 '11': 274,
 'urgent': 7235,
 '800': 645,
 '09050003091': 175,
 'c52': 1605,
 'valid12hrs': 7277,
 'sindu': 6203,
 'birla': 1362,
 'soft': 6316,
 'harish': 3355,
 'rent': 5727,
 'transfred': 7049,
 'acnt': 802,
 'any': 1000,
 'plm': 5270,
 'stash': 6480,
 'ran': 5589,
 'dry': 2487,
 'last': 4046,
 'night': 4789,
 'until': 7213,
 'sunday': 6627,
 'wen': 7482,
 'bcums': 1269,
 'angry': 974,
 'wid': 7534,
 'seriously': 6057,
 'coz': 2058,
 'being': 1309,
 'most': 4612,
 'true': 7078,
 'way': 7441,
 'showing': 6161,
 'deep': 2225,
 'affection': 854,
 'luv': 4289,
 'kettoda': 3944,
 'manda': 4361,
 'nice': 4784,
 'god': 3175,
 'found': 2977,
 'glad': 3159,
 'xafter': 7671,
 'msgs': 4644,
 'cst': 2105,
 'ntwk': 4866,
 'chg': 1789,
 'year': 7704,
 'supply': 6644,
 'cds': 1710,
 'store': 6530,
 'choice': 1814,
 'worth': 7633,
 '500': 544,
 '100': 261,
 'weekly': 7471,
 'txt': 7124,
 'music': 4674,
 '87066': 698,
 'ts': 7089,
 'cs': 2102,
 'www': 7667,
 'ldew': 4072,
 'subs16': 6583,
 '1win150ppmx3': 342,
 'trip': 7069,
 'tiring': 6937,
 'uni': 7187,
 'starts': 6477,
 'cos': 2029,
 'taking': 6717,
 'modules': 4579,
 'jus': 3900,
 'concentrating': 1959,
 'final': 2862,
 'yr': 7744,
 'yesterday': 7717,
 'nvm': 4880,
 'wear': 7450,
 'sport': 6435,
 'shoes': 6134,
 'anyway': 1009,
 'speak': 6390,
 'hmm': 3473,
 'did': 2311,
 'email': 2585,
 'balance': 1212,
 '600': 577,
 'next': 4780,
 'question': 5551,
 'complete': 1942,
 'landmark': 4031,
 'big': 1349,
 'bob': 1416,
 'barry': 1239,
 'ben': 1319,
 '83738': 678,
 'luck': 4282,
 'pls': 5272,
 'preferably': 5395,
 'pap': 5086,
 'very': 7307,
 'slowly': 6268,
 'loads': 4190,
 'hour': 3535,
 'water': 7431,
 'congratulation': 1978,
 'started': 6475,
 'skye': 6238,
 'wake': 7389,
 'im': 3633,
 'bored': 1441,
 'inever': 3687,
 'id': 3608,
 'exciting': 2712,
 'happened': 3342,
 'yup': 7753,
 'went': 7483,
 'hair': 3314,
 'hope': 3511,
 'head': 3385,
 'hurt': 3581,
 'ploughing': 5271,
 'through': 6899,
 'pile': 5232,
 'ironing': 3763,
 'staying': 6488,
 'chinky': 1808,
 'round': 5854,
 'boys': 1479,
 'hot': 3529,
 'pics': 5221,
 'porn': 5328,
 '69855': 600,
 '24hrs': 369,
 '50p': 549,
 'stop': 6522,
 'stopbcm': 6524,
 'sf': 6079,
 'wc1n3xx': 7444,
 'teach': 6756,
 'apps': 1045,
 'college': 1908,
 'mila': 4500,
 'age23': 874,
 'blonde': 1401,
 'new': 4772,
 'look': 4220,
 'sex': 6072,
 'guys': 3297,
 'mtalk': 4647,
 '69866': 601,
 '18': 323,
 '30pp': 441,
 '1st': 336,
 '5free': 564,
 'increments': 3675,
 'help08718728876': 3421,
 'none': 4824,
 'nowhere': 4860,
 'ikno': 3626,
 'doesdiscount': 2398,
 'shitinnit': 6127,
 'book': 1430,
 'which': 7517,
 'after': 863,
 'sth': 6506,
 'specs': 6398,
 'membership': 4463,
 'px3748': 5540,
 'fri': 3014,
 'expect': 2728,
 'welcome': 7478,
 'lots': 4241,
 'presents': 5411,
 'nicky': 4787,
 'sounds': 6370,
 'great': 3248,
 'customer': 2138,
 'representative': 5746,
 'freephone': 3004,
 '0808': 64,
 '145': 301,
 '4742': 511,
 'between': 1336,
 '9am': 742,
 '11pm': 282,
 '1000': 262,
 '5000': 545,
 'meeting': 4449,
 'really': 5632,
 'side': 6180,
 'long': 4216,
 'does': 2397,
 'yet': 7718,
 'spiritual': 6417,
 'thk': 6878,
 'shld': 6130,
 'wana': 7405,
 'lessons': 4107,
 'stretch': 6546,
 'wanted': 7410,
 'legal': 4093,
 'advice': 846,
 'gary': 3091,
 'split': 6424,
 'make': 4347,
 'ptbo': 5508,
 'everything': 2687,
 'babe': 1192,
 'problem': 5451,
 'spending': 6407,
 'lot': 4239,
 'quality': 5547,
 'oops': 4972,
 'somerset': 6331,
 'far': 2793,
 'tomo': 6986,
 'didn': 2313,
 'spring': 6443,
 'early': 2522,
 'thanx': 6830,
 'puttin': 5536,
 'fone': 2938,
 'down': 2444,
 'semester': 6034,
 'ass': 1110,
 'enjoy': 2614,
 'doggy': 2406,
 'style': 6574,
 'mon': 4589,
 'okie': 4938,
 'gd': 3107,
 'la': 4010,
 'ex': 2703,
 'oso': 5016,
 'depends': 2261,
 'whether': 7516,
 'eat': 2533,
 'western': 7492,
 'chinese': 1807,
 'den': 2252,
 'prefer': 5394,
 'figure': 2849,
 'suppose': 6646,
 'couple': 2048,
 'different': 2325,
 'dates': 2186,
 'masters': 4397,
 'pleassssssseeeeee': 5266,
 'tel': 6773,
 'avent': 1164,
 'done': 2422,
 'sportsx': 6436,
 '25': 372,
 'pass': 5114,
 'name': 4699,
 'joke': 3864,
 'fees': 2825,
 'university': 7195,
 'florida': 2914,
 'seem': 6015,
 'holla': 3490,
 'matthew': 4413,
 '09063440451': 213,
 'landline': 4029,
 'complimentary': 1948,
 'lux': 4292,
 'tenerife': 6788,
 'holiday': 3489,
 'await': 1170,
 'collection': 1907,
 'ppm150': 5369,
 'sae': 5901,
 'box334': 1464,
 'sk38xh': 6229,
 'splashmobile': 6421,
 '1000s': 264,
 'gr8': 3225,
 'tones': 6990,
 'each': 2517,
 'wk': 7583,
 'subscrition': 6590,
 'costing': 2033,
 '300p': 436,
 'credit': 2079,
 'kick': 3954,
 'road': 5827,
 'spun': 6447,
 'spk': 6418,
 'mo': 4562,
 'dead': 2199,
 'wrld': 7653,
 'sleeping': 6248,
 'cool': 2015,
 'nytho': 4888,
 'tx': 7123,
 'fonin': 2941,
 'hon': 3495,
 '2mwen': 413,
 'bk': 1375,
 'frmcloud': 3025,
 'valentine': 7274,
 'game': 3078,
 'dis': 2353,
 'answers': 993,
 'someone': 6328,
 'loves': 4261,
 'ques': 5550,
 'colour': 1910,
 'suits': 6615,
 'rply': 5863,
 'pleasure': 5267,
 'pain': 5069,
 'trouble': 7073,
 'pours': 5361,
 'rain': 5574,
 'sum1': 6618,
 'hurts': 3583,
 'becoz': 1284,
 'current': 2131,
 'alone': 931,
 'guy': 3296,
 'loving': 4263,
 'xam': 7672,
 'hall': 3321,
 'boy': 1475,
 'asked': 1102,
 'term': 6792,
 'answer': 989,
 'manage': 4356,
 'own': 5052,
 'hesitation': 3440,
 'lookin': 4223,
 'silently': 6191,
 'intha': 3736,
 'ponnungale': 5316,
 'ipaditan': 3755,
 '26th': 379,
 'july': 3894,
 'awesome': 1176,
 'lemme': 4097,
 'whenever': 7508,
 'stubborn': 6559,
 'hospital': 3525,
 'kept': 3940,
 'telling': 6777,
 'mark': 4380,
 'weak': 7446,
 'sucker': 6596,
 'hospitals': 3526,
 'suckers': 6597,
 'thanks': 6825,
 'congrats': 1977,
 'special': 6392,
 'cinema': 1831,
 'yours': 7737,
 '09061209465': 195,
 'suprman': 6649,
 'matrix3': 4410,
 'starwars3': 6479,
 'etc': 2660,
 'bx420': 1600,
 'ip4': 3753,
 '5we': 572,
 '150pm': 311,
 'bathe': 1249,
 'liao': 4114,
 'sleep': 6246,
 'nite': 4801,
 'place': 5245,
 'usf': 7255,
 'charge': 1746,
 'contribute': 2001,
 'greatly': 3250,
 'appreciated': 1038,
 'yeah': 7703,
 'leave': 4087,
 'barely': 1232,
 'sane': 5924,
 'fighting': 2846,
 'constantly': 1991,
 'helping': 3423,
 'drive': 2470,
 'em': 2584,
 'someplace': 6330,
 'probably': 5450,
 'while': 7518,
 'nothing': 4848,
 'eating': 2536,
 'esplanade': 2657,
 'into': 3737,
 'usc': 7249,
 'payment': 5143,
 'portal': 5330,
 'another': 986,
 'explain': 2740,
 'weekend': 7469,
 'pretty': 5421,
 'pissed': 5239,
 'off': 4911,
 'hiya': 3467,
 'paying': 5142,
 'account': 793,
 'pleasant': 5263,
 'surprise': 6657,
 'checked': 1767,
 'statements': 6482,
 'acc': 780,
 'life': 4122,
 'lifetime': 4125,
 'may': 4420,
 'meaningless': 4435,
 'moments': 4587,
 'spent': 6408,
 'means': 4436,
 'itself': 3789,
 'al': 905,
 'moan': 4563,
 'thin': 6866,
 'goes': 3177,
 'wrong': 7655,
 'fault': 2805,
 'de': 2198,
 'arguments': 1068,
 'fed': 2817,
 ...}

In [46]:
v.get_feature_names_out()[777]

'abusers'

In [47]:
from sklearn.naive_bayes import MultinomialNB

In [48]:
model =MultinomialNB()

In [49]:

model.fit(X_train_cv,y_train)

MultinomialNB()

In [51]:
X_test_cv=v.transform(X_test)

In [54]:
type(X_test_cv)

scipy.sparse._csr.csr_matrix

In [55]:
X_test_cv.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3, 7766))

In [56]:
from sklearn.metrics import classification_report

In [59]:
y_pred= model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       960
           1       0.99      0.92      0.95       155

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [84]:
email =["""Dear Team,

I hope you are doing well.

This is a reminder that our project meeting is scheduled for tomorrow at 10:00 AM in the conference room. We will discuss the current progress, upcoming tasks, and any challenges we are facing.

Please review the project updates before the meeting and bring any questions or suggestions you may have.

Thank you, and I look forward to seeing everyone tomorrow.

Best regards,
Shohag
"""]
text =["""Always have no discount , but today 100% discount """]

In [85]:
predic_email = v.transform(text)

In [86]:
model.predict(predic_email)

array([0])