In [1]:
import pandas as pd
import numpy as np

import nltk
import string
import spacy
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [2]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /home/shohag-
[nltk_data]     rana/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/shohag-
[nltk_data]     rana/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
df = pd.read_csv("Emotion_Sentiment_DataSet.csv")

In [4]:
df.head(10)

   Unnamed: 0                                               Text Emotion
0           0  i feel jealous becasue i wanted that kind of l...    love
1           1  i feel like she has taken on the role of a gra...    love
2           2  i feel like im back to the arms of a beloved l...    love
3           3  i am feeling so festive right now and not just...    love
4           4  i don t discuss even my feelings for beloved w...    love
5           5  i also love seeing a star emerge and i feel li...    love
6           6  im feeling kinda shaky my mind is full of doub...    love
7           7  i love running because i feel strong and power...    love
8           8  i feel that popular bloggers dont post with fr...    love
9           9  i can never fall in love with anyone because m...    love

In [5]:
df.shape

(160000, 3)

In [6]:
df.columns

Index(['Unnamed: 0', 'Text', 'Emotion'], dtype='str')

In [7]:
df.isnull().sum()

Unnamed: 0    0
Text          8
Emotion       0
dtype: int64

In [8]:
df["Emotion"].value_counts()

Emotion
love          39553
happiness     27175
sadness       17481
Normal        16351
hate          15267
anger         12336
Depression    10333
fun           10075
surprise       6954
worry          4475
Name: count, dtype: int64

In [9]:
df=df.drop(columns=["Unnamed: 0"])

In [10]:
df.head()

                                                Text Emotion
0  i feel jealous becasue i wanted that kind of l...    love
1  i feel like she has taken on the role of a gra...    love
2  i feel like im back to the arms of a beloved l...    love
3  i am feeling so festive right now and not just...    love
4  i don t discuss even my feelings for beloved w...    love

In [11]:
nlp = spacy.load("en_core_web_trf")

In [12]:
def tokenize(text):
    if pd.isna(text):
        return []
    doc = nlp(str(text))
    return [token.text for token in doc]
df["tokens"] =df["Text"].apply(tokenize)

KeyboardInterrupt:

In [ ]:
print(df[["Text", "tokens"]])